### ISSUE TITLE
Some functions in `SlydifiOverlay` have counterintuitive names

### ISSUE THREAD

**Issue by na4zagin3** [monaqa/slydifi#19]
The current version has the following conditional functions. 
IMO some of them should be renamed.

|Name|Behavior|Proposal|
|----|----|----|
|`only n`|`n-layer == n`|keep|
|`elsewhen n`|`not (only n)`| can we replace this with [`negate : ('a -> bool) -> 'a -> bool`](https://ocaml.org/api/Fun.html#VALnegate) |
|`till n`|`n-layer <= n`|it's a matter of taste, but why not rename to `until` to align with Beamer which has `\untilSlide` |
|`after n`|`n-layer >= n`| rename to `from` because “after” is non-inclusive (`n-layer > n`) |
|`during m n`| `(n-layer >= m) && (n-layer <= n)`| rename for `between` because it's more typical. |
|`in-case nlst`|`nlst` includes the current layer number `n-layer`|rename for `on-slides` |

**Comment by monaqa** [comment]
Thank you so much for your suggestion!
We have included the changes you mentioned in the v0.4.0 release.
