### ISSUE TITLE
READMEのminimum.satyのエラー

### ISSUE THREAD

**Issue by estis75** [monaqa/slydifi#23]
README.mdを読んでminimum.satyをコンパイルしてみようと思ったんですが，そのままだと
```
! [Type Error] at "minimum.saty", line 3, characters 0-8:
    undefined variable 'document'.
```
というエラーが出るので以下のように書き換えて動くようにしました．
```
@require: class-slydifi/theme/plain

SlydifiPlain.document (|
  draft-mode = false;
|) '<
  +frame{\SLyDIFi; のテスト}<
    +p{Hello, \SLyDIFi;!}
  >
>
```
README.mdやexample/*のコードを読んでみたところ，全体に渡ってmodule名やdocumentの第一引数が省略されていますが，それでコンパイルできるようにできる方法がありましたらご教示いただけると助かります．

よろしくお願いします．

**Comment by monaqa** [comment]
インストールされている SLyDIFi のバージョンが古いと思われます。最新版 (`v0.4.0`) にして試していただけますか？

**Comment by estis75** [comment]
確かにSATySFi及びSLyDIFiのバージョンが低いままでした……
バージョンアップしたら動きました．ありがとうございます！
